SachOnline/Controllers/SachOnlineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;

namespace SachOnline.Controllers
{
    public class SachOnlineController : Controller
    {
        // GET: SachOnline
        QLBanSachEntities data = new QLBanSachEntities();
        
        /// <summary> /// LaySachMoi /// </summary>
        // <param name="count">int</param>
        /// <returns>List</returns>
        private List<SACH> LaySachMoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        // GET: SachOnline
        public ActionResult Index()
        {
            //Lay 6 quyen sach moi
            var listSachMoi = LaySachMoi(6); 
            return View(listSachMoi);
        }
        public ActionResult ChuDePartial()
        {
            var listChuDe = from cd in data.CHUDEs select cd; 
            return PartialView(listChuDe);
        }
        private List<SACH> LaySachBanNhieu(int count = 6)
        {
            return data.SACHes.OrderByDescending(item => item.SoLuongBan).Take(count).ToList();
        }
        public ActionResult SachBanNhieuPartial()
        {
            var ds = LaySachBanNhieu(6);
            return PartialView(ds);
        }
        public ActionResult NavPartial()
        {
            return PartialView();
        }
        public ActionResult SachTheoChuDe(int id)
        {
            var sach = from s in data.SACHes where s.MaCD==id select s;
            return View(sach);
        }
        public ActionResult SachTheoNhaXuatBan(int id)
        {
            var nhaxuatban = from s in data.SACHes where s.MaNXB == id select s;
            return View(nhaxuatban);
        }
        public ActionResult NhaXuatBanPartial()
        {
            var listNhaXuatBan = from cd in data.NHAXUATBANs select cd; 
            return PartialView(listNhaXuatBan);
        }
        public ActionResult ChiTietSach(int id)
        {
            var sach = from s in data.SACHes where s.MaSach == id select s;
            return View(sach.Single());
        }
       
    }


}

 

SachOnline/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SachOnline.Models;

namespace SachOnline.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        [HttpGet]
        public ActionResult Dangky()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
        QLBanSachEntities data = new QLBanSachEntities();
        [HttpPost]
        public ActionResult Dangky(FormCollection collection, KHACHHANG kh)
        {
            
            //Gan cac gia tri nguoi dung nhap du lieu cho cac bien
            var sHoTen = collection["HoTen"];
            var sTenDN = collection["TenDN"];
            var sMatKhau = collection["Matkhau"];
            var sMatKhauNhapLai = collection["MatKhauNL"];
            var sDiachi = collection["Diachi"];
            var sEmail = collection["Email"];
            var sDienThoai = collection["DienThoai"];
            var dNgaySinh = String.Format("{0:MM/dd/yyyy}", collection["NgaySinh"]);
            if (string.IsNullOrEmpty(sHoTen))
            {
                ViewData["err1"] = "Họ tên không được rỗng";
            }
            else if (String.IsNullOrEmpty(sTenDN))
            {
                ViewData["err2"] = "Tên đăng nhập không được rỗng";
            }
            else if (String.IsNullOrEmpty(sMatKhau))
            {
                ViewData["err3"] = "Phải nhập mật khẩu";
            }
            else if (String.IsNullOrEmpty(sMatKhauNhapLai))
            {
                ViewData["err4"] = "Phải nhập lại mật khẩu";
            }
            else if (sMatKhau != sMatKhauNhapLai)
            {
                ViewData["err4"] = "Mật khẩu nhập lại không khớp";
            }
            else if (String.IsNullOrEmpty(sEmail))
            {
                ViewData["err5"] = "Email không được rỗng";
            }
            else if (String.IsNullOrEmpty(sDienThoai))
            {
                ViewData["err6"] = "Số điện thoại không được rỗng";
            }
            else if (data.KHACHHANGs.SingleOrDefault(n => n.TenDN == sTenDN) != null)
            {
                ViewBag.ThongBao = "Tên đăng nhập đã tồn tại";
            }
            else if (data.KHACHHANGs.SingleOrDefault(n => n.Email == sEmail) != null)
            {
                ViewBag.ThongBao = "Email đã được sử dụng";
            }
            else
            {
                kh.HoTenKH = sHoTen;
                kh.TenDN = sTenDN;
                kh.MatKhau = sMatKhau;
                kh.Email = sEmail;
                kh.DiaChiKH = sDiachi;
                kh.DienThoaiKH = sDienThoai;
                kh.NgaySinh = DateTime.Parse(dNgaySinh);
                data.KHACHHANGs.Add(kh);
                data.SaveChanges();
                return RedirectToAction("DangNhap");
            }
            return this.Dangky();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var sTenDN = collection["TenDn"];
            var sMatKhau = collection["MatKhau"];
            if(String.IsNullOrEmpty(sTenDN))
            {
                ViewData["Err1"] = "Bạn chưa nhập tên đăng nhập";
            }
            else if(String.IsNullOrEmpty(sMatKhau))
            {
                ViewData["Err2"] = "Phải nhập mật khẩu";
            }
            else
            {
                KHACHHANG kh = data.KHACHHANGs.SingleOrDefault(n => n.TenDN == sTenDN && n.MatKhau == sMatKhau);
                if(kh != null)
                {
                    ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                    Session["TaiKhoan"] = kh;
                }
                else
                {
                    ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
                
            }
            return View();
        }

    }

}

SachOnline/Views/SachOnline/ChiTietSach.cshtml
@model SachOnline.Models.SACH
    @{
        ViewBag.Title = "ChiTietSach";
        Layout = "~/Views/Shared/_LayoutUser.cshtml";
    }

    <div class="thumbnail">

        <h4 class="tensach">
            <b>@Model.TenSach</b>
        </h4>

        <img src="/Images/Sach/@Model.HinhMinhHoa" alt="@Model.TenSach">
        <div class="motasach">
            <p>
                @Html.Raw(@Model.MoTa.ToString().Replace("\n", "</p><p>&nbsp&nbsp&nbsp&nbsp&nbsp"))
            </p>
        </div>

        <p class="ngaycapnhat"> Ngày cập nhật: @Html.FormatValue(@Model.NgayCapNhat, "{0:dd/MM/yyyy}") </p>
        <p class="glaban"> Giá bán: <span>@Html.FormatValue(@Model.DonGia, "{0:#,##0}") VNĐ</span></p>
        <p class="addtocard">
            <a href="@Url.Action("ThemGioHang","GioHang", new { ms = Model.MaSach, url = Request.Url.ToString() })"
               class="btn btn-primary" role="button">
                <span class="glyphicon glyphicon-shopping-cart"
                      aria-hidden="true"></span> Add to Cart
            </a>
        </p>
    </div>

SachOnline/Views/SachOnline/ChuDePartial.cshtml
@model IEnumerable<SachOnline.Models.CHUDE>
<ul class="list-group">
    <li class="list-group-item active" style="font-weight:bold; text-align:center">SÁCH THEO CHỦ ĐỀ</li>
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SachTheoChuDe","SachOnline", new { id = item.MaCD})"
           class="list-group-item">@item.TenChuDe</a>
    }
</ul>

SachOnline/Views/SachOnline/Index.cshtml
@model IEnumerable<SachOnline.Models.SACH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2 class="text-center">SÁCH MỚI</h2>
<hr>
<div class="row text-center">
    @foreach (SachOnline.Models.SACH sach in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-6">
            <div class="thumbnail">
                <img src="~/Images/Sach/@sach.HinhMinhHoa" alt="Thumbnail Image 1" class="img- responsive img-rounded imgbook" style="width:400px;">  <div class="caption">
                    <h4 style="min-height:70px;">
                        <a href="@Url.Action("ChiTietSach","SachOnline", new { id = sach.MaSach})">@sach.TenSach</a>
                    </h4>
                    <p>
                        <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sach.MaSach, url = Request.Url.ToString() })" class="btn btn-primary" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

<nav class="text-center">
    <!-- Add class .pagination-lg for larger blocks or .pagination-sm for smaller blocks-->
    <ul class="pagination">
        <li>
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="active"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li class="disabled"><a href="#">5</a></li>
        <li>
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

@section SachBanNhieuPartial{
    @Html.Action("SachBanNhieuPartial", "SachOnline")
}

SachOnline/Views/SachOnline/NavPartial.cshtml
<nav class="navbar navbar-inverse">
    <!--navbar-fixed-top-->
    <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar1" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">SachOnline</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">TRANG CHỦ</a> </li>
                <li><a href="#">GIỚI THIỆU</a> </li>
                <li><a href="#">LIÊN HỆ</a> </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">Người dùng<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Dangky","User")"><span class="glyphicon glyphicon-user"></span> Đăng ký</a> </li>
                        <li role="separator" class="divider"></li>
                        <li><a href="@Url.Action("Dangnhap","User")"><span class="glyphicon glyphicon-log-in"></span> Đăng nhập</a></li>
                    </ul>
                </li>
                <li>@Html.Action("GioHangPartial", "GioHang")</li>
            </ul>

            <form class="navbar-form navbar-right" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Tìm kiếm">
                </div>
                <button type="submit" class="btn btn-default">Tìm</button>
            </form>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-->
</nav>


<div class="container">
    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div id="carousel1" class="carousel slide">
                <ol class="carousel-indicators">
                    <li data-target="#carousel1" data-slide-to="0" class="active"> </li>
                    <li data-target="#carousel1" data-slide-to="1" class=""> </li>
                    <li data-target="#carousel1" data-slide-to="2" class=""> </li>
                    <li data-target="#carousel1" data-slide-to="3" class=""> </li>
                    <li data-target="#carousel1" data-slide-to="4" class=""> </li>
                    <li data-target="#carousel1" data-slide-to="5" class=""> </li>
                </ol>
                <div class="carousel-inner">

                    <div class="item active">
                        <img class="img-responsive" src="Images/Slider/01.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 1 </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="Images/Slider/02.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 2 </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="Images/Slider/03.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 3 </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="Images/Slider/04.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 4 </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="Images/Slider/05.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 5 </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="Images/Slider/06.jpg" alt="thumb">
                        <div class="carousel-caption"> Quảng cáo 6 </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel1" data-slide="prev"><span class="icon-prev"></span></a> <a class="right carousel-control" href="#carousel1" data-slide="next"><span class="icon-next"></span></a>
            </div>
        </div>
    </div>
    <hr>
</div>

SachOnline/Views/SachOnline/SachTheoChuDe.cshtml
@model IEnumerable<SachOnline.Models.SACH>
@{
    ViewBag.Title = "SachTheoChuDe";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2 class="text-center">SÁCH THEO CHỦ ĐỀ</h2>
<hr>
<div class="row text-center">
    @foreach (SachOnline.Models.SACH sach in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-6">
            <div class="thumbnail">
                <img src="~/Images/Sach/@sach.HinhMinhHoa" alt="Thumbnail Image 1" class="img- responsive img-rounded imgbook" style="width:400px;">  <div class="caption">
                    <h4 style="min-height:70px;">
                        <a href="@Url.Action("ChiTietSach","SachOnline", new { id = sach.MaSach})">@sach.TenSach</a>
                    </h4>
                    <p>
                        <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sach.MaSach, url = Request.Url.ToString() })" class="btn btn-primary" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-
                                  hidden="true"></span> Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

SachOnline/Views/SachOnline/SachTheoNhaXuatBan.cshtml
@{
    ViewBag.Title = "SachTheoNhaXuatBan";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2 class="text-center">SÁCH THEO NHÀ XUẤT BẢN</h2>
<hr>
<div class="row text-center">
    @foreach (SachOnline.Models.SACH sach in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-6">
            <div class="thumbnail">
                <img src="~/Images/Sach/@sach.HinhMinhHoa" alt="Thumbnail Image 1" class="img- responsive img-rounded imgbook" style="width:400px;">  <div class="caption">
                    <h4 style="min-height:70px;">
                        <a href="@Url.Action("ChiTietSach","SachOnline", new { id = sach.MaSach})">@sach.TenSach</a>
                    </h4>
                    <p>
                        <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sach.MaSach, url = Request.Url.ToString() })" class="btn btn-primary" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-
                                  hidden="true"></span> Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>